from fastapi.testclient import TestClient
import pytest

from app.main import app
from app.schemas.learner import LearnerRecommendation
from app.schemas.vectors import VectorSearchHit
from app.services.learner_analysis import (
    LocalLlmUnavailableError,
    generate_recommendation,
    search_learner_evidence,
)


def test_analyze_learner_profile(monkeypatch) -> None:
    async def fake_similarity_search(text: str, role_query: str = "") -> list[VectorSearchHit]:
        assert "Skillset: SQL, Excel, stakeholder interviews" in text
        assert role_query == "Data Analyst"
        return [
            VectorSearchHit(
                id="business-analyst",
                score=0.92,
                payload={
                    "role": "Business Analyst",
                    "skills": ["SQL", "Process mapping", "Dashboarding"],
                    "source": "test-taxonomy",
                },
            )
        ]

    monkeypatch.setattr(
        "app.routers.learner.similarity_search",
        fake_similarity_search,
    )

    async def fake_generate_recommendation(profile_text, matches):
        return (
            LearnerRecommendation(
                next_roles=["Data Analyst"],
                priority_skills=["SQL", "Dashboarding"],
                actions_today=["Build one dashboard."],
                explanation="Generated by local LLM.",
            ),
            "local",
        )

    monkeypatch.setattr(
        "app.routers.learner.generate_recommendation",
        fake_generate_recommendation,
    )

    with TestClient(app) as client:
        response = client.post(
            "/learner/analyze",
            json={
                "current_role": "Customer Support Specialist",
                "target_interest": "Data Analyst",
                "skillset": "SQL, Excel, stakeholder interviews",
                "resume_text": "Handled customer escalations and weekly reporting.",
            },
        )

    assert response.status_code == 200
    body = response.json()
    assert body["llm_provider"] == "local"
    assert body["similar_matches"][0]["id"] == "business-analyst"
    assert body["recommendation"]["next_roles"][0] == "Data Analyst"
    assert "SQL" in body["recommendation"]["priority_skills"]


def test_analyze_learner_profile_requires_skillset_or_resume() -> None:
    with TestClient(app) as client:
        response = client.post(
            "/learner/analyze",
            json={
                "current_role": "Customer Support Specialist",
                "target_interest": "Data Analyst",
            },
        )

    assert response.status_code == 422


def test_analyze_learner_profile_requires_target_interest() -> None:
    with TestClient(app) as client:
        response = client.post(
            "/learner/analyze",
            json={
                "current_role": "Customer Support Specialist",
                "skillset": "SQL, Excel, stakeholder interviews",
            },
        )

    assert response.status_code == 422


def test_analyze_learner_profile_validates_target_interest() -> None:
    with TestClient(app) as client:
        response = client.post(
            "/learner/analyze",
            json={
                "current_role": "Customer Support Specialist",
                "target_interest": "123 !!!",
                "skillset": "SQL, Excel, stakeholder interviews",
            },
        )

    assert response.status_code == 422


def test_analyze_learner_profile_returns_502_when_llm_fails(monkeypatch) -> None:
    async def fake_similarity_search(text: str, role_query: str = "") -> list[VectorSearchHit]:
        return [
            VectorSearchHit(
                id="data-analyst",
                score=0.9,
                payload={"role": "Data Analyst", "skills": ["SQL"], "source": "test"},
            )
        ]

    async def fake_generate_recommendation(profile_text, matches):
        raise LocalLlmUnavailableError("local llm unavailable")

    monkeypatch.setattr("app.routers.learner.similarity_search", fake_similarity_search)
    monkeypatch.setattr("app.routers.learner.generate_recommendation", fake_generate_recommendation)

    with TestClient(app) as client:
        response = client.post(
            "/learner/analyze",
            json={
                "current_role": "Customer Support Specialist",
                "target_interest": "Data Analyst",
                "skillset": "SQL, Excel, stakeholder interviews",
            },
        )

    assert response.status_code == 502
    assert response.json()["detail"] == "Local LLM failed to generate a valid response."


def test_search_learner_evidence_uses_role_column_first() -> None:
    class FakeVectorDbClient:
        def __init__(self) -> None:
            self.calls: list[str] = []

        def find_role_records(self, role_query: str, limit: int = 5) -> list[VectorSearchHit]:
            self.calls.append("job_skills.find_role_records")
            assert role_query == "Data Analyst"
            assert limit == 3
            return [
                VectorSearchHit(
                    id="job-role-data-analyst",
                    score=1.0,
                    payload={"record_type": "job_role", "role": "Data Analyst"},
                )
            ]

        def search_text(
            self,
            text: str,
            limit: int = 5,
            where: dict[str, object] | None = None,
        ) -> list[VectorSearchHit]:
            self.calls.append("job_skills.search_text")
            assert "Skillset: SQL" in text
            assert limit == 8
            assert where == {"role": "Data Analyst"}
            return [
                VectorSearchHit(
                    id="role-skill-data-analyst-sql",
                    score=0.84,
                    payload={
                        "record_type": "role_skill",
                        "role": "Data Analyst",
                        "skill": "SQL",
                    },
                )
            ]

        def search_unique_skills_text(
            self,
            text: str,
            limit: int = 5,
            where: dict[str, object] | None = None,
        ) -> list[VectorSearchHit]:
            self.calls.append("unique_skills.search_text")
            assert "Skillset: SQL" in text
            assert limit == 5
            assert where is None
            return [
                VectorSearchHit(
                    id="unique-skill-sql",
                    score=0.8,
                    payload={
                        "record_type": "unique_skill",
                        "skill": "SQL",
                        "description": "Query and manage relational data.",
                    },
                )
            ]

    fake_client = FakeVectorDbClient()
    matches = search_learner_evidence(
        text="Skillset: SQL",
        role_query="Data Analyst",
        client=fake_client,
    )

    assert [match.id for match in matches] == [
        "job-role-data-analyst",
        "role-skill-data-analyst-sql",
        "unique-skill-sql",
    ]
    assert fake_client.calls == [
        "job_skills.find_role_records",
        "job_skills.search_text",
        "unique_skills.search_text",
    ]


@pytest.mark.anyio
async def test_generate_recommendation_raises_when_local_llm_fails() -> None:
    class BrokenLocalLlm:
        async def recommend(self, profile_text, matches):
            raise ValueError("invalid local model output")

    with pytest.raises(LocalLlmUnavailableError):
        await generate_recommendation(
            profile_text="Skillset: SQL",
            matches=[],
            client=BrokenLocalLlm(),
        )


@pytest.mark.anyio
async def test_generate_recommendation_uses_local_llm() -> None:
    class WorkingLocalLlm:
        async def recommend(self, profile_text, matches):
            return LearnerRecommendation(
                next_roles=["AI Product Analyst"],
                priority_skills=["Product metrics"],
                actions_today=["Review one dashboard."],
                explanation="Generated by local LLM.",
            )

    recommendation, provider = await generate_recommendation(
        profile_text="Skillset: metrics",
        matches=[],
        client=WorkingLocalLlm(),
    )

    assert provider == "local"
    assert recommendation.next_roles == ["AI Product Analyst"]
