import json

import httpx
import pytest

from app.clients.local_llm import LocalLlmClient, build_recommendation_prompt, compress_evidence
from app.schemas.vectors import VectorSearchHit


@pytest.mark.anyio
async def test_local_llm_client_parses_ollama_json_response() -> None:
    requests: list[httpx.Request] = []

    async def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        return httpx.Response(
            200,
            json={
                "response": json.dumps(
                    {
                        "next_roles": ["Data Analyst"],
                        "priority_skills": ["SQL", "Python"],
                        "actions_today": ["Build a dashboard from a small dataset."],
                        "explanation": "Matched against analyst evidence.",
                    }
                )
            },
        )

    client = LocalLlmClient(
        base_url="http://local-llm.test",
        model="llama-test",
        provider="ollama",
        enabled=True,
        transport=httpx.MockTransport(handler),
    )

    recommendation = await client.recommend(
        profile_text="Skillset: SQL",
        matches=[
            VectorSearchHit(
                id="data-analyst",
                score=0.91,
                payload={"role": "Data Analyst", "skills": ["SQL"]},
            )
        ],
    )

    assert recommendation is not None
    assert recommendation.next_roles == ["Data Analyst"]
    assert recommendation.priority_skills == ["SQL", "Python"]
    assert requests[0].method == "POST"
    assert requests[0].url.path == "/api/generate"
    assert json.loads(requests[0].read())["model"] == "llama-test"


@pytest.mark.anyio
async def test_local_llm_client_parses_openai_compatible_response() -> None:
    requests: list[httpx.Request] = []

    async def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        return httpx.Response(
            200,
            json={
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "next_roles": ["AI Product Analyst"],
                                    "priority_skills": ["Experiment design"],
                                    "actions_today": ["Draft one experiment plan."],
                                    "explanation": "Generated by local OpenAI-compatible model.",
                                }
                            )
                        }
                    }
                ]
            },
        )

    client = LocalLlmClient(
        base_url="http://local-llm.test",
        model="glm-4.7-flash",
        provider="openai-compatible",
        enabled=True,
        transport=httpx.MockTransport(handler),
    )

    recommendation = await client.recommend(profile_text="Skillset: Product metrics", matches=[])

    assert recommendation is not None
    assert recommendation.next_roles == ["AI Product Analyst"]
    assert recommendation.priority_skills == ["Experiment design"]
    assert requests[0].method == "POST"
    assert requests[0].url.path == "/v1/chat/completions"
    assert json.loads(requests[0].read())["model"] == "glm-4.7-flash"


@pytest.mark.anyio
async def test_local_llm_client_returns_none_when_disabled() -> None:
    client = LocalLlmClient(enabled=False)

    recommendation = await client.recommend(profile_text="Skillset: SQL", matches=[])

    assert recommendation is None


def test_build_recommendation_prompt_compacts_large_vector_payloads() -> None:
    prompt = build_recommendation_prompt(
        profile_text="Resume: " + ("large resume " * 600),
        matches=[
            VectorSearchHit(
                id="data-analyst",
                score=0.91,
                payload={
                    "role": "Data Analyst",
                    "skills": ["SQL", "Python"],
                    "description": "Analyse datasets and build dashboards.",
                    "document": "very large indexed document " * 600,
                    "documents": ["another giant document " * 600],
                },
            )
        ],
    )

    assert "Data Analyst" in prompt
    assert "SQL" in prompt
    assert "Analyse datasets and build dashboards." in prompt
    assert "very large indexed document" not in prompt
    assert len(prompt) < 5_000


def test_compress_evidence_groups_by_role() -> None:
    compressed = compress_evidence(
        [
            VectorSearchHit(
                id="data-analyst-sql",
                score=0.9,
                payload={
                    "role": "Data Analyst",
                    "skill": "SQL",
                    "description": "Query datasets.",
                },
            ),
            VectorSearchHit(
                id="data-analyst-python",
                score=0.8,
                payload={
                    "role": "Data Analyst",
                    "skill": "Python",
                    "task": "Build dashboards",
                },
            ),
        ]
    )

    assert len(compressed) == 1
    assert compressed[0]["role"] == "Data Analyst"
    assert compressed[0]["skills"] == ["SQL", "Python"]
    assert compressed[0]["tasks"] == ["Build dashboards"]


@pytest.mark.anyio
async def test_local_llm_client_extracts_resume_profile() -> None:
    async def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            json={
                "choices": [
                    {
                        "message": {
                            "content": json.dumps(
                                {
                                    "current_role": "Data Analyst",
                                    "skillset": ["SQL", "Python", "Dashboarding"],
                                    "summary": "Analyst with reporting experience.",
                                }
                            )
                        }
                    }
                ]
            },
        )

    client = LocalLlmClient(
        base_url="http://local-llm.test",
        model="glm-4.7-flash",
        provider="openai-compatible",
        enabled=True,
        transport=httpx.MockTransport(handler),
    )

    profile = await client.extract_resume_profile("Experience: Data Analyst. Skills: SQL.")

    assert profile is not None
    assert profile.current_role == "Data Analyst"
    assert profile.skillset == "SQL, Python, Dashboarding"
